name: Feature Branch Workflow

on:
  push:
    branches:
      - "feature/**"

jobs:
  build-test-pr:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2. Setup .NET
      - name: Setup .NET 8
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: "8.0.x"

      # 3. Restore
      - name: Restore dependencies
        run: dotnet restore ./app/Pathways.Api.csproj

      # 4. Build
      - name: Build
        run: dotnet build ./app/Pathways.Api.csproj --configuration Release --no-restore

      # 5. Test
      - name: Test
        run: dotnet test ./tests/Pathways.Api.Tests.csproj --configuration Release --verbosity normal

      # 6. Criar Pull Request para develop
      - name: Create Pull Request to develop
        if: success()
        uses: peter-evans/create-pull-request@v6
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.ref_name }}
          base: develop
          title: "Auto PR from ${{ github.ref_name }} to develop"
          body: |
            This PR was automatically generated from branch `${{ github.ref_name }}`.
            It passed build and tests successfully.
          labels: |
            feature
            auto-pr
