name: Release CD

on:
  push:
    branches:
      - "release/*"

jobs:
  build-test-merge:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout
      - name: Checkout
        uses: actions/checkout@v3

      # 2. Setup .NET
      - name: Setup .NET 8
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: "8.0.x"

      # 3. Restore
      - name: Restore dependencies
        run: dotnet restore ./app/Pathways.Api.csproj

      # 4. Build
      - name: Build
        run: dotnet build ./app/Pathways.Api.csproj --configuration Release --no-restore

      # 5. Test (comando atualizado)
      - name: Run tests
        run: dotnet test ./tests/Pathways.Api.Tests.csproj --configuration Release --verbosity normal

      # 6. Build Docker Image (opcional, só validação)
      - name: Build Docker image
        run: docker build -t pathways-api:test ./app

      # 7. Criar Pull Request automático para main
      - name: Create PR release → main
        uses: repo-sync/pull-request@v2
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          source_branch: ${{ github.ref_name }} # release/*
          destination_branch: main
          pr_title: "Auto PR from ${{ github.ref_name }} to main"
          pr_body: |
            This PR was automatically generated from branch `${{ github.ref_name }}`.
            ✅ Build and tests passed successfully.
